#!/usr/bin/parallel --shebang-wrap /usr/bin/env bash
. tbz-common.sh

FINISHED_OPTIPNG=false
STILL_WORKING=true

QUIET=false
MULTI=false
INPUTS=()
ORIGPNG=""

for arg; do
	if [ "$arg" = "--quiet" ] ; then
		QUIET=true
	elif [ -z "$ORIGPNG" ] ; then
		ORIGPNG="$arg"
		INPUTS+=("$ORIGPNG")
	else
		MULTI=true
		INPUTS+=("$arg")
	fi
done

if [ -z "$ORIGPNG" ] ; then
	error "Usage: $(basename "$0") filename.png ..."
fi

if $MULTI; then
	for INPUT in "${INPUTS[@]}"; do
		if ! [ -e "$INPUT" ] ; then
			error "Can't find: $INPUT"
		fi
	done
	if check "$QUIET"; then
		QUIETARG="--quiet"
	else
		QUIETARG=""
	fi
	for INPUT in "${INPUTS[@]}"; do
		shecho "$0" $QUIETARG "$INPUT"
	done | parallel --lb
	exit 0
fi

if check "$QUIET"; then
	STDOUT="/dev/null"
	STDERR="/dev/null"
else
	STDOUT="/dev/stderr"
	STDERR="/dev/stderr"
fi

if check "$QUIET"; then
	OQUIET="-quiet"
else
	OQUIET=" "	
fi

TEMPPNG="$ORIGPNG".$RANDOM.crushpng_tempout.png
while [ -e "$TEMPPNG" ] ; do
	TEMPPNG="$ORIGPNG".$RANDOM.crushpng_tempout.png
done

BAKPNG="$ORIGPNG".$RANDOM.crushpng_backup.png
while [ -e "$BAKPNG" ] ; do
	BAKPNG="$ORIGPNG".$RANDOM.crushpng_backup.png
done

clup() {
	if check "$FINISHED_OPTIPNG" ; then
		if $STILL_WORKING ; then
			note "Received signal, cleaning up."
		fi
		rm -f "$TEMPPNG"
		cp -f --attributes-only --preserve=all "$BAKPNG" "$ORIGPNG"
		rm -f "$BAKPNG"
	else
		note "Received signal, restoring from backup."
		cp --preserve=all "$BAKPNG" "$ORIGPNG"
		rm -f "$TEMPPNG"
		rm -f "$BAKPNG"
		rm -f "$ORIGPNG".bak
	fi
}

add_cleanup_routine clup

cp --preserve=all "$ORIGPNG" "$BAKPNG"

optipng $OQUIET -fix -force -preserve -zc9 -zm8 -zs1 -f5 "$ORIGPNG"
#truepng "$ORIGPNG" /force /zc9 /zm8 /zs1 /fe /a1 /i0 /md remove all >$STDOUT
FINISHED_OPTIPNG=true

zopflipng -y -m --filters=04mep "$ORIGPNG" "$TEMPPNG" >$STDOUT
mv -f "$TEMPPNG" "$ORIGPNG"
STILL_WORKING=false
