#!/usr/bin/env python3

import sys
import base64
import zlib

if len(sys.argv) <= 1:
    sys.exit(1)

tail = sys.argv[1].removeprefix('https://traneptora.com/api/v0/random/')
comp_uri = base64.b64decode(tail, altchars=b'-_', validate=True)
payload = zlib.decompress(comp_uri, wbits=-9)
if len(payload) == 0:
    raise ValueError("Empty Payload")
count = payload[0]
if count == 0:
    raise ValueError("No Content")
index = 1
maxlen = len(payload)
urls = []
for i in range(count):
    if index + 4 >= maxlen:
        raise ValueError("Not Enough Space for Length")
    length = int.from_bytes(payload[index : index+4], byteorder='little', signed=False)
    index += 4
    if length == 0 or index + length > maxlen:
        raise ValueError("Bad Length")
    url = payload[index : index + length].decode()
    index += length
    urls += [url]
for url in urls:
    print(url)
