#!/bin/sh

if [ "$#" -eq 0 ] ; then
	printf "Usage: %s <URL> [waifu2x opts]\n" "${0##*/}"
	exit 1
fi

URL="$1"; shift
TEMPDL="$(mktemp)"
TEMPFIN="$(mktemp --suffix=.png)"
TEMP_A="$(mktemp --suffix=.png)"

# Download the file
ffmpeg -y -i "$URL" -map v -vf libplacebo=format=gbrp16le -c png -f image2pipe -update 1 -frames 1 "$TEMPFIN"

# Here's where we actually decrud it
waifu2x-ncnn-vulkan -i "$TEMPFIN" -o "$TEMP_A" -s 1 -n 3 "$@"

# We add a small bit of selective blur for compression ratio
# and we turn it back to an 8-bit png
convert "$TEMP_A" -selective-blur 0x1+0.5% -depth 8 "$TEMPFIN"

# remove the temporary file
rm -f "$TEMP_A"

# Re-encode the png to reduce filesize a little bit
optipng -zc1 -zm1 -zs0 -f5 "$TEMPFIN"
png-zopfli-idat <"$TEMPFIN" | sponge "$TEMPFIN"

# Write the filename of the PNG file to stdout
printf 'Finished!\n%s\n' "$TEMPFIN"

if [ -n "$DISPLAY" ] ; then
	# copy it into the Rich X clipboard, so we can just paste it into whatever
	# Or upload with another script
	xclip -i -selection clipboard -t image/png <"$TEMPFIN"

	# copy the filename into the Plain X clipboard
	printf '%s' "$TEMPFIN" | xclip

	# And preview it with Eye of Mate
	eom "$TEMPFIN"
fi
