#!/bin/sh
set -e; set -f; set -u

if [ -n "${DISPLAY+x}" ] ; then
	if [ "$(id -u)" -eq 0 ] ; then
		exec pluma --new-window "$@"
	else
		exec subl --new-window --wait "$@"
	fi
else
	exec nano "$@"
fi
