#!/usr/bin/env python3

import sys
import base64
import zlib

payload = b''

for url in sys.argv[1:]:
    pay = url.encode()
    payload += len(pay).to_bytes(length=4, byteorder='little', signed=False) + pay

payload = len(sys.argv[1:]).to_bytes(length=1) + payload

zpay = zlib.compress(payload, wbits=-9)
b64pay = base64.b64encode(zpay, altchars=b'-_').decode()

print('https://traneptora.com/api/v0/random/' + b64pay)
