#!/bin/sh
set -e
set +H

if [ $# -le 0 ] ; then
	echo "Usage: $(basename "$0") <command>"
	exit 1
fi

if ! daemon --help </dev/null >/dev/null 2>/dev/null; then
	echo "\"daemon\" not found in your PATH."
	exit 1
fi

COMM="$(basename "$1")"
LOG=~/.local/share/log/launch-"$COMM".log
mkdir -p ~/.local/share/log/
daemon --inherit --safe -o "$LOG" -D "$PWD" -- "$@" || ( echo "Failed to launch." && exit 2 )
