#!/bin/sh
. tbz-common.sh

if is_set DISPLAY; then
	if ! iamroot ; then
		if command_exists subl; then
			my_editor="${my_editor-subl}"
		fi
	fi
	if command_exists pluma; then
		my_editor="${my_editor-pluma}"
	elif command_exists gedit; then
		my_editor="${my_editor-gedit}"
	elif command_exists kwrite; then
		my_editor="${my_editor-kwrite}"
	elif command_exists "$EDITOR"; then
		my_editor="${my_editor-$EDITOR}"
	fi
fi

if command_exists nano; then
	my_editor="${my_editor-nano}"
elif command_exists vim; then
	my_editor="${my_editor-vim}"
elif command_exists emacs; then
	warning "...really? emacs?"
	my_editor="${my_editor-emacs}"
else
	error "No editor found!"
fi

num_args="$#"

i=1; while [ "$i" -le "$num_args" ]; do
	eval "arg_num_${i}=\"\${$i}\""
i=$((1+$i)); done
set --
i=1; while [ "$i" -le "$num_args" ]; do
	eval "arg=\"\${arg_num_${i}}\""
	if command_exists "$arg"; then
		myfile="$(command -v "$arg")"
	else
		myfile="$arg"
	fi
	myfile="$(readlink -f "$myfile")"
	encoding="$(file --brief --mime-encoding "$myfile")"
	if fmatches "$encoding" 'binary'; then
		printf '%s is a binary file.\n'	"$myfile"
	else
		set -- "$@" "$myfile"
	fi
i=$((1+$i)); done

exec "$my_editor" "$@"
