#!/bin/sh

patch_image() {
    if ! [ -f "$1" ] ; then
        printf >&2 '%s: %s: No such file or directory\n' "${0##*/}" "$1"
        return 1
    fi

    esc_name=$(printf '%sx' "$1" | sed 's/\\/\\\\/g' | sed 's/\"/\\\"/g')
    esc_name="${esc_name%x}"

    gimp -nidfs --batch-interpreter plug-in-script-fu-eval -b '(script-fu-mtg-corners "'"$esc_name"'")' --quit
    crush-image "$1"
}

ret=0

for arg; do
    if ! patch_image "$arg"; then
        ret=1
    fi
done

exit "$ret"
