#!/bin/sh

cracklib="/usr/share/cracklib/cracklib-small"

if ! [ -r "$cracklib" ] ; then
    cracklib=/usr/local/share/cracklib/cracklib-small
fi

if ! [ -r "$cracklib" ] ; then
    printf '%s: %s\n' "${0##*/}" 'cracklib not found'
    exit 1
fi

sort -R "$cracklib" | head -n 4 | awk -v ORS=- '{print $1}' | sed -E 's/([^a-zA-Z0-9_\-]|-$)//' | xargs printf 'Df1!2@%s' | head -c 32 && echo
