#!/bin/sh

if [ "$#" -lt 1 ] ; then
	printf >&2 'error: Provide a filename.\nUsage: %s <image>\n' "${0##*/}"
fi

if [ "$1" = "--rotate" ] ; then
	argextra="-rotate '-90<'"
else
	argextra=''
fi

input_file="$1"
input_filename="${input_file##*/}"
input_base="${input_filename%.*}"
input_ext="${input_filename#"$input_base"}"
tpng="$(mktemp --suffix=.png)"
tpng2="$(mktemp --suffix=.png)"
ffmpeg -y -i "$input_file" "$tpng2"
width="$(magick identify -format '%w' "$tpng2")"
height="$(magick identify -format '%h' "$tpng2")"
magick "$tpng2" ${argextra} -filter Catrom -resize '1280x1280>' "$tpng"
if [ "$input_ext" = ".jpg" ] ; then
	timg="$(mktemp --suffix="$input_ext")"
	magick "$tpng" "$timg"
else
	timg="$tpng"
fi
xclip -i -selection clipboard -t image/png <"$tpng"
eom "$timg"
sh -c 'sleep 10; rm -f -- "$@"' "$0" "$tpng" "$timg"
