#!/bin/sh
. tbz-common.sh

if [ "$#" -lt 1 ] ; then
	error "Provide a filename." "Usage: $this_exe image"
fi

input_file="$1"
tpng="$(mktemp --suffix=.png)"
tjpeg="/tmp/$(basename "$input_file")"
tjpeg="${tjpeg%.*}.jpg"
convert "$input_file" -auto-orient -filter mitchell -resize 1088x816 "$tpng"
cjpeg -q 97 <"$tpng" >"$tjpeg"
rm -f -- "$tpng"
