#!/bin/bash
. tbz-common.sh

if [ $# -le 1 ] ; then
	echo "$(basename $0) file_in file_out [--noise-level=X] [--scale-ratio=X] [--type={anime,photo}] [--gpu=X] [--w2x={caffe,w2xc}]"
	exit 0
fi

fname=""
file_out=""
scale_ratio=""
noise_level=""
W2X=""
model=""
gpu=""

for arg; do
	if [[ "$arg" =~ ^--noise-level= ]] ; then
		noise_level="${arg#--noise-level=}"
	elif [[ "$arg" =~ ^--scale-ratio= ]] ; then
		scale_ratio="${arg#--scale-ratio=}"
	elif [[ "$arg" =~ ^--type= ]] ; then
		model="${arg#--type=}"
	elif [[ "$arg" =~ ^--gpu= ]] ; then
		gpu="${arg#--gpu=}"
	elif [[ "$arg" =~ ^--w2x= ]] ; then
		W2X="${arg#--w2x=}"
	elif [ -z "$fname" ] ; then
		fname="$arg"
	elif [ -z "$file_out" ] ; then
		file_out="$arg"
	else
		error "Invalid Trailing Argument: $arg"
	fi
done

if [ ! -e "$fname" ] ; then
	error "Cannot find: $fname"
fi

if [ -z "$noise_level" ] ; then
	noise_level=0
fi

if [ -z "$scale_ratio" ] ; then
	scale_ratio=1
fi

if [ "$noise_level" = 0 ] && [ "$scale_ratio" = 1 ] ; then
	warning "Not denoising or scaling. Nothing much will happen."
fi

noise_level=$((-1 + "$noise_level"))

if [ -z "$W2X" ] ; then
	CAFFE=false
elif [ "$W2X" = "caffe" ] ; then
	CAFFE=true
elif [ "$W2X" = "w2xc" ] ; then
	CAFFE=false
else
	error "Invalid Waifu2x type: $W2X"
fi

# Use photo model?
if [ -z "$model" ] ; then
	photo="False"
elif [ "$model" = "anime" ] ; then
	photo="False"
elif [ "$model" = "photo" ] ; then
	photo="True"
else 
	error "Invalid picture type: $model"
fi

if [ -z "$gpu" ] ; then
	gpu="-1"
fi

clup() {
	rm -f "$tempin".ffindex
	rm -f "$tempin"
}

add_cleanup_routine clup

#fname="$(readlink -f "$1")"
#file_out="$2"

#width=$(identify -format '%w' "$fname")
#height=$(identify -format '%h' "$fname")
#pix_fmt=$(ffprobe -v error -show_entries stream=pix_fmt -of default=noprint_wrappers=1:nokey=1 "$fname")


_return_var=tempoutp temp_suffix=png create_temp_file
_return_var=tempout temp_suffix=raw create_temp_file
_return_var=tempin temp_suffix=png create_temp_file
_return_var=tempscript temp_suffix=vpy create_temp_file

cat >"$tempscript" <<EOF
import vapoursynth as vs
core = vs.core

# waifu2x requires RGBS
# RGBS is Single Precision RGB float, i.e. rgb32f

clip = core.ffms2.Source(source=image_in)

def get_plane(clip, plane):
	return core.std.ShufflePlanes(clips=[clip], planes=[plane], colorfamily=vs.GRAY)

if (type(clip) is list):
	have_alpha=True
	rgbclip=clip[0]
	aclip=clip[1]
else:
	have_alpha=False
	rgbclip=clip

rgbclip = core.resize.Point(rgbclip, format=vs.RGBS, range_in_s='full', range_s='full')
if (have_alpha):
	aclip = core.resize.Point(aclip, format=vs.RGBS, range_in_s='full', range_s='full')
EOF

if checkvar CAFFE; then
# start waifu2x-caffe
cat >>"$tempscript" <<EOF
# The noise level is off by 1
rgbclip = core.caffe.Waifu2x(rgbclip, noise=(int(noise_level) - 1), scale=int(scale_ratio), model=(4 if (photo == 'True') else 3), processor=(0 if (int(gpu) < 0) else int(gpu)))
if (have_alpha):
	aclip = core.caffe.Waifu2x(aclip, noise=(int(noise_level) - 1), scale=int(scale_ratio), model=(4 if (photo == 'True') else 3), processor=(0 if (int(gpu) < 0) else int(gpu)))
else:
	aclip = core.std.BlankClip(rgbclip, format=vs.RGBS, color=[1.0, 1.0, 1.0])
EOF
# end waifu2x-caffe
else
# start waifu2x-w2xc
cat >>"$tempscript" <<EOF
rgbclip = core.w2xc.Waifu2x(rgbclip, noise=int(noise_level), scale=int(scale_ratio), photo=(photo == 'True'), processor=int(gpu))
if (have_alpha):
	aclip = core.w2xc.Waifu2x(aclip, noise=int(noise_level), scale=int(scale_ratio), photo=(photo == 'True'), processor=int(gpu))
else:
	aclip = core.std.BlankClip(rgbclip, format=vs.RGBS, color=[1.0, 1.0, 1.0])
EOF
# end waifu2x-w2xc
fi

cat >>"$tempscript" <<EOF
rgbclip = core.resize.Bilinear(rgbclip, format=vs.RGB24, range_in_s='full', range_s='full')
aclip = core.resize.Bilinear(aclip, format=vs.GRAY8, matrix_s='709', range_in_s='full', range_s='full')
clip = core.std.Splice([get_plane(rgbclip, 1), get_plane(rgbclip, 2), get_plane(rgbclip, 0), aclip])
clip.set_output()
EOF

convert "$fname" "$tempin"

runwaifu2x(){

	width=$(identify -format '%w' "$tempin")
	height=$(identify -format '%h' "$tempin")

	newwidth=$(printf '%.0f' "$(__ readfrom "$width * $scale_ratio_temp" bc -l)")
	newheight=$(printf '%.0f' "$(__ readfrom "$height * $scale_ratio_temp" bc -l)")
	new2xwidth=$(($width * $scale_ratio_2x))
	new2xheight=$(($height * $scale_ratio_2x))

	vspipe --arg image_in="$tempin" --arg noise_level="$noise_level" --arg scale_ratio="$scale_ratio_2x" --arg photo="$photo" --arg gpu="$gpu" "$tempscript" "$tempout"
	ffmpeg -hide_banner -y -f rawvideo -video_size "${new2xwidth}x${new2xheight}" -pixel_format gbrap -i "$tempout" "$tempoutp"
	#waifu2x-ncnn-vulkan -i "$tempin" -o "$tempoutp" -n "$noise_level" -s "$scale_ratio_2x"
	optipng -force -zc6 -zm8 -zs0 -f0 "$tempoutp"
	if [ "$photo" = "True" ] ; then
		convert "$tempoutp" -filter mitchell -resize "${newwidth}x${newheight}" "$tempin"
	else
		convert "$tempoutp" -filter Catrom -resize "${newwidth}x${newheight}" "$tempin"
	fi
}

while (( "$( bc -l <<<"$scale_ratio > 2.0" )" )) ; do
	note "Using Waifu2x more than once for a better image."
	scale_ratio_temp=2
	scale_ratio_2x=2
	runwaifu2x
	scale_ratio=$(bc -l <<<"$scale_ratio / 2.0")
done

if (( "$( bc -l <<<"$scale_ratio > 1.0" )" )) ; then
	note "Scale ratio between 1 and 2. Upscaling 2x then downscaling (if necessary)."
	scale_ratio_temp="$scale_ratio"
	scale_ratio_2x=2
	runwaifu2x
else
	scale_ratio_temp="$scale_ratio"
	scale_ratio_2x=1
	runwaifu2x
fi

mv -f "$tempin" "$file_out"
