#!/bin/sh
. tbz-common.sh
include tbz-uploader-common.sh

if [ $# -lt 1 ] ; then
	reading_from_stdin="true"
	_return_var=filename temp_suffix="log" create_temp_file
	cat >"$filename"
else
	reading_from_stdin="false"
	filename="$1"; shift
fi

tbz_uploader_common "-Ffile=@${filename}" "--url" "https://0x0.st" "$@"

if check "${reading_from_stdin-}" ; then
	rm -f "$filename"
fi
