#!/bin/sh
set -e

if [ -z "$1" ] ; then
	>&2 echo "$(basename "$0") file_or_directory"
	exit 1
fi 

if [ ! -d "$1" ] ; then
	exec lz4 -9 -z "$1" "$1".lz4
fi

namd=$(printf "%s" "$1" | tr -d '/' )

if [ -z "$namd" ] ; then
	>&2 echo "Please do not create an archive of / with this command."
	exit 1
fi

exsorttar --lz4 "$namd".tar.lz4 "$1"

du -ms "${namd}.tar.lz4"
du -ms "$1"

