#!/bin/sh
set -e

this_exe="$0"

usage(){
	print_usage
	exit 1
}

print_usage(){
	printf '%s\n' "Usage: $(basename "$this_exe") <mode> <command>"
}

if [ $# -le 1 ] ; then
	usage
fi

this_dir="$(dirname "$this_exe")"
my_mode="$1"; shift
my_safe_comm="$(printf %s "$*" | tr -cd '[^A-Za-z0-9_\-\.]')"
my_service="$HOME"/.config/systemd/user/persist-"$my_safe_comm".service
cat >"$my_service" <<EOF
[Unit]
Description=Dummy Persist Service

[Service]
Type=simple
Restart=always
EOF
echo "ExecStart=/usr/bin/env" "$@" >>"$my_service"
echo "WorkingDirectory=$PWD" >>"$my_service"

systemctl --user daemon-reload
systemctl --user "$my_mode" persist-"$my_safe_comm".service
rm -f "$my_service"
