#!/bin/sh
. tbz-common.sh
include tbz-uploader-common.sh

if [ $# -lt 1 ] ; then
	error "Invalid usage." "Usage: $this_script file_to_upload [curl opts]"
fi

filename="$1"; shift

set -- "-Ffile=@$filename" "--url" "https://0x0.st" "$@"
tbz_uploader_common "$@"
