#!/bin/sh
set -e

if [ -z "$1" ] ; then
	>&2 echo "$(basename "$0") filename.png [denoiseropts] "
	exit 1
else
	fname="$1"; shift
fi

TEMPFILE="$(mktemp --suffix=.png)"
waifu2x-denoiser "$fname" "$TEMPFILE" "$@"
mv -f "$TEMPFILE" "$fname"
rm -f "$TEMPFILE"
