#!/bin/bash
set -e

if [ $# -eq 0 ] ; then
	if [ -t 2 ] ; then
		>&2 echo "Please don't dryrun this from a terminal. Use \"launch\"."
		exit 1
	else
		exit 0
	fi
fi

COMM="$(basename "$1")"
mkdir -p ~/.local/share/log/
LOG=~/.local/share/log/launch-"$COMM".log

clup() {
	#echo >>"$LOG"
	#echo "--------" >>"$LOG"
	#echo >>"$LOG"
	#touch "$LOG".lz4
	#cat <(lz4 -d "$LOG".lz4 - 2>~/.log/launch-"$COMM"-lz4status.log) "$LOG" | lz4 -z - - 2>>~/.log/launch-"$COMM"-lz4status.log >"$LOG".lz4.2
	#mv "$LOG".lz4.2 "$LOG.lz4"
	gzip -9 <"$LOG" >"$LOG.gz"
	rm -f "$LOG"
}

trap clup EXIT


# This is intentionally not exec "$@"
# Otherwise the exit trap would not work
"$@"
