#!/bin/bash
set -e

if [ $# -le 0 ] ; then
	echo "Usage: $(basename $0) <command>"
	exit 1
fi

COMM="$(basename "$1")"
LOG=~/.log/launch-"$COMM".log
mkdir -p ~/.log/
daemon --inherit --safe -o "$LOG" -D "$PWD" -- launch-wrapper $@ || ( echo "Failed to launch." && exit 2 )
echo "Successfully launched. Output is appended to ~/.log/launch-$COMM.log.lz4"
exit 0
