#!/bin/bash
set -e

COMM="$(basename "$1")"
LOG=~/.log/persist-"$COMM".log

clup() {
	echo >>"$LOG"
	echo "--------" >>"$LOG"
	echo >>"$LOG"
	cat <(lz4 -d "$LOG".lz4 - 2>~/.log/persist-"$COMM"-lz4status.log) "$LOG" | lz4 -z - - 2>>~/.log/persist-"$COMM"-lz4status.log >"$LOG".lz4.2
	mv "$LOG".lz4.2 "$LOG.lz4"
	rm -f "$LOG"
}

trap clup EXIT

$@

