#!/bin/bash
set -e

usage(){
	echo "Usage:" "$(basename $0)" "start|stop" "command"
	exit 1
}

if [ $# -le 1 ] ; then
	usage
fi

if ! pgrep --help </dev/null >/dev/null 2>/dev/null; then
	echo "\"pgrep\" not found in your PATH."
	exit 1
fi


if ! daemon --help </dev/null >/dev/null 2>/dev/null; then
	echo "\"daemon\" not found in your PATH."
	exit 1
fi

if ! launch-wrapper </dev/null >/dev/null 2>/dev/null; then
	echo "\"launch-wrapper\" not found in your PATH."
	echo "Did you remember to install that as well?"
	exit 1
fi



COMM="$(basename "$2")"
LOG=~/.log/launch-"$COMM".log
case "$1" in
	start)
		MODE=start
		shift
		mkdir -p ~/.log/
		daemon --name="$COMM" --respawn --inherit --safe -o ~/.log/persist-"$COMM".log -D "$PWD" -- persist-wrapper "$@"
		if [ $? == 0 ] ; then
			echo "Successfully launched. Output is appended to ~/.log/persist-$COMM.log"
			exit 0
		else
			echo "Failed to launch."
			exit 2
		fi
		;;
	stop)
		MODE=stop
		shift
		if ! daemon --running --name="$COMM"; then
			echo "Not running!"
			exit 1
		fi
		PCOMM="pgrep -f '^daemon --name=$COMM'"
		pidlist=()
		while pidlist+=($(sh -c "$PCOMM" | xargs pgrep -P)); do
			PCOMM="$PCOMM | xargs pgrep -P"
		done
		daemon --stop --name="$COMM"
		if kill ${pidlist[@]} 2>/dev/null; then
			echo "Successfully stopped."
			exit 0
		else
			echo "Failed to stop."
			exit 2
		fi
		;;
	*)
		usage
		;;
esac
exit 0

