#!/bin/bash
set -e

if [ $# -eq 0 ] ; then
	if [ -t 2 ] ; then
		>&2 echo "Please don't dryrun this from a terminal. Use \"persist\"."
		exit 1
	else
		exit 0
	fi
fi

COMM="$(basename "$1")"
mkdir -p ~/.local/share/log/
LOG=~/.local/share/log/persist-"$COMM".log

clup() {
	gzip -9 <"$LOG" >"$LOG.gz"
	rm -f "$LOG"
}

trap clup EXIT

# This is intentionally not exec "$@"
# Otherwise the exit trap would not work
"$@"
