#!/bin/sh
set -e
set +H

usage(){
	print_usage
	exit 1
}

print_usage(){
	echo "Usage: $(basename "$0") start|stop <command>"
}

if [ $# -le 1 ] ; then
	usage
fi

if ! daemon --help </dev/null >/dev/null 2>/dev/null; then
	echo "\"daemon\" not found in your PATH."
	exit 1
fi

COMM="$(basename "$2")"
mkdir -p ~/.local/share/log/
LOG=~/.local/share/log/persist-"$COMM".log

case "$1" in
	start)
		MODE=start
		shift
		# --respawn is the whole point
		if daemon --name="$COMM" --respawn --inherit --safe -o "$LOG" -D "$PWD" -- "$@" ; then
			echo "Successfully launched. Output is written to $LOG"
			exit 0
		else
			echo "Failed to launch."
			exit 2
		fi
		;;
	stop)
		MODE=stop
		shift
		if ! daemon --running --name="$COMM"; then
			echo "The command \"$COMM\" is not currently persisting via this script."
			exit 1
		fi

		if daemon --stop --name="$COMM"; then
			echo "Successfully stopped."
			exit 0
		else
			echo "Failed to stop."
			exit 2
		fi
		;;
	--help)
		print_usage
		exit 0
		;;
	*)
		usage
		;;
esac
