#!/bin/sh

usage(){
	echo "Usage:" "$(basename $0)" "start|stop" "command"
	exit 1
}

if [ $# -le 1 ] ; then
	usage
fi

COMM="$2"
case "$1" in
	start)
		MODE=start
		shift
		mkdir -p ~/.log/
		daemon --name="$COMM" --respawn --inherit --safe -o ~/.log/persist-"$COMM".log -D "$PWD" -- $@
		if [ $? == 0 ] ; then
			echo "Successfully launched. Output is appended to ~/.log/persist-$1.log"
			exit 0
		else
			echo "Failed to launch."
			exit 2
		fi
		;;
	stop)
		MODE=stop
		shift
		daemon --stop --name="$COMM"
		if [ $? == 0 ] ; then
			echo "Successfully stopped."
			exit 0
		else
			echo "Failed to stop."
			exit 2
		fi
		;;
	*)
		usage
		;;
esac

exit $?

