#!/bin/sh

daemon --name=x11vnc --inherit --safe --respawn --acceptable=10 --attempts=10 --delay=10 --limit=10 -- x11vnc -usepw -forever -many -noxdamage -auth ~/.Xauthority -display :0 -shared -o /var/log/x11vnc.log


