#!/bin/sh

while read line; do
	if ( echo "$line" | grep ,, >/dev/null ) ; then
		transline=$(trans -no-auto -brief $1 "$(echo "$line" | sed 's/.*,,\(.*\)/\1/')")
		echo -n "$line" | sed 's/\(.*,,\).*/\1/'
		echo "$transline"
	else
		echo $line
	fi
done

