#!/bin/sh
set -e; set +H

while read line; do
	if ( printf %s "$line" | grep -q ,, ) ; then
		# Yes, really, this is three quotes deep
		transline="$(trans -no-auto -brief "$1" "$(printf %s "${line}\n" | sed 's/.*,,\(.*\)/\1/')")"
		printf %s "$line" | sed 's/\(.*,,\).*/\1/'
		printf '%s\n' "$transline"
	else
		printf '%s\n' "$line"
	fi
done

