#!/bin/sh
set -e

rm -f .subs-playass.ass
fname="$(basename "$1")"
ffmpeg -y -i "$1" -map 0:s -c:s copy .subs-playass.ass
# This cost me several hours of confusion before I realized this is necessary
# Google Translate will complain about carriage returns
dos2unix .subs-playass.ass
trans_fname="${fname}.translated.ass"
if [ ! -e "$trans_fname" ] ; then
	cat .subs-playass.ass | translate-ass "$2" | tee "$trans_fname"
fi
rm -f .subs-playass.ass
exec mpv "$1" --sub-file="$trans_fname"

