#!/bin/sh

while true; do
	if [ "$1" -gt 1 2>/dev/null ] ; then
		numw="$1"
	else
		numw=1
	fi
	for i in $(seq "${numw}"); do
		printf "%s " "$(randomword | sed "s/'s\$//" )"
	done
	echo
	sleep 1
done

